Added Winston library for logging
alertlogic/al-aws-collector-js pull request #73
Opened 2021-12-21 14:27 UTC by rakhimundhada15

Added the Winston library to improve logging for lambda functions.

2021-12-21 15:09 UTC, scott-jones-AlertLogic approved these changes
Looks good, thank you Rakhi!

2021-12-22 12:44 UTC, kkuzmin requested changes
@rakhimundhada15 thanks. LGTM but some minor comments.

2021-12-22 12:44 UTC, kkuzmin commented on logger/index.js
> +        errors({ stack: true }),
I think we don't need stack for all errors. We only need them for exceptions and for errors which are handles gracefully we normally don't need a stack trace. Is is possible to pass this parameter into `logger.error()`?

2021-12-22 12:44 UTC, kkuzmin commented on index.js
> +    logger: require('./logger')
Please keep all export names consistent - `Logger`

2021-12-22 14:23 UTC, kkuzmin commented on logger/index.js
> +        errors({ stack: true }),
Let's expose error options through env var as well, like `LOG_ERROR_OPTS`

2021-12-22 15:12 UTC, kkuzmin commented on logger/index.js
> +const showStack = process.env.LOG_ERROR_OPTS ? { stack: process.env.LOG_ERROR_OPTS } : {};
I suggest we pass `LOG_ERROR_OPTS ` as is, like
```
process.env.LOG_ERROR_OPTS ? JSON.parse(process.env.LOG_ERROR_OPTS) : {};
```

2021-12-23 12:17 UTC, kkuzmin approved these changes

2021-12-27 10:51 UTC, merged